spring:
  profiles:
    include: config
  application:
    name: newletter-core
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://keycloak-service/realms/ma-plateforme/protocol/openid-connect/token/introspect
